#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           flipper,       tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           flywheelLeft,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveLeftFront, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveLeftMiddle, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveLeftBack, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           driveRightFront, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           driveRightMiddle, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveRightBack, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           flywheelRight, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          conveyor,      tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#include "mapping.c"
#include "utils.c"
#include "atomic.c"
#include "tasks.c"
#include "helpers.c"
#include "controllers.c"

// ---- MAIN CONTROL

void pre_auton() {
	// stop tasks while changing from autonomous to usercontrol
	bStopTasksBetweenModes = true;
}

task autonomous() {
	enableEncoderDrive = false;

	bool isRed = false;
	driveFlipped = isRed;
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	while (getLeftDriveEncoder() < 800) {
		moveDrive(127, 80);
		moveFlipper(-127);
	}
	moveDrive(0, 0);
	moveFlipper(-60);
	wait1Msec(1000);
	while (getLeftDriveEncoder() > 750) {
		moveDrive(-127, -80);
		moveFlipper(-60);
	}
	moveDrive(0, 0);
	wait1Msec(1000);
	while (getLeftDriveEncoder() > 360) {
		moveDrive(-127, 110);
	}
	moveDrive(0, 0);
	while (abs(getLeftDriveEncoder()) < 950) {
		moveDrive(107, 70);
		moveFlipper(127);
	}
	moveDrive(0, 0);
	moveFlipper(127);
	wait1Msec(1700);
	moveFlipper(0);
}

task usercontrol() {
	//startTask(autonomous);
	//wait1Msec(30000);
	driveFlipped = false;
	startUsercontrolTasks();
	enableEncoderDrive = false;
	while (true) {
		doDrive();
		doConveyor();
		doFlywheel();
		doFlipper();
	}
}
