#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           flipper,       tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           flywheelLeft,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveLeftFront, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveLeftMiddle, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveLeftBack, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           driveRightFront, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           driveRightMiddle, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveRightBack, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           flywheelRight, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          conveyor,      tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#include "mapping.c"
#include "utils.c"
#include "atomic.c"
#include "tasks.c"
#include "helpers.c"
#include "controllers.c"

// ---- MAIN CONTROL

void pre_auton() {
	// stop tasks while changing from autonomous to usercontrol
	bStopTasksBetweenModes = true;
}

 task autonomous() {
	// turn
	//driveDistance(100, 100, -100);
}

task usercontrol() {
	startAllTasks();
	while (true) {
		doDrive();
		doConveyor();
		doFlywheel();
		doFlipper();
		// Encoder test
		if (vexRT[Btn7U]) {
			driveStraight(100, 24);
		} else if (vexRT[Btn7D]) {
			driveStraight(100, -24);
		}
		// override gradual spinup
		if (vexRT[Btn8U]) {
			moveFlywheel(127);
			flywheelSpeed = 127;
		}
		if (vexRT[Btn8D]) {
			moveFlywheel(0);
			flywheelSpeed = 0;
		}
	}
}
